### PR TITLE
Feature/paragraphs itemnames

### PR DESCRIPTION
**Pull request by LennardWesterveld**

### CODE REVIEW

**Comment by rolfvandekrol** [comment]
Looks pretty cool to me. Could you implement `hook_kw_itemnames_entity_disabled_entity_types` to make sure the `kw_itemnames_entity` doesn't interfere with your module? Example implementation in https://github.com/kraftwagen/kw-itemnames/blob/master/entity/kw_itemnames_entity.module#L26-L32

**Comment by LennardWesterveld** [comment]
Yea i can do that, this weekend or next week i will.

**Comment by rolfvandekrol** [comment]
:+1:

**Comment by LennardWesterveld** [comment]
@rolfvandekrol can you check it again :)?

**Comment by rolfvandekrol** [comment]
@LennardWesterveld 

The formatting looks good to me. 

`hook_kw_itemnames_entity_disabled_entity_types` is not in the `kw_itemnames` group, so can't be implemented in `*.kw_itemnames.inc`.

**Comment by LennardWesterveld** [comment]
@rolfvandekrol oh my bad :) fixing it right now

**Comment by rolfvandekrol** [comment]
And, it's merged in! Thanks for your work!

**Comment by LennardWesterveld** [comment]
np, @rolfvandekrol take also a look at my D8 kraftwagen testing branches and trello :)

**Pull request merged**
